# Generated by Django 3.2.25 on 2024-12-28 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20241227_1851'),
        ('quiz', '0004_auto_20241227_1740'),
        ('student', '0007_auto_20241227_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Note Quiz',
                'verbose_name_plural': 'Notes Quiz',
                'ordering': ['-date_update'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='school.cours')),
                ('quiz_scores', models.ManyToManyField(through='student.QuizGrade', to='quiz.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student.student')),
            ],
            options={
                'verbose_name': 'Note Étudiant',
                'verbose_name_plural': 'Notes Étudiants',
                'ordering': ['-date_update'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='quizgrade',
            name='student_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_grades', to='student.studentgrade'),
        ),
        migrations.AlterUniqueTogether(
            name='quizgrade',
            unique_together={('student_grade', 'quiz')},
        ),
    ]
