# Generated by Django 3.2.25 on 2024-12-27 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20241227_1739'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20241227_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_limite', models.DateTimeField(default=quiz.models.get_default_end_date)),
                ('points_max', models.FloatField(default=20.0)),
                ('fichier_instruction', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.cours')),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
                'ordering': ['-date_limite'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_reponse', models.FileField(upload_to='assignment_submissions/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('note', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soumission de devoir',
                'verbose_name_plural': 'Soumissions de devoirs',
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.quizattempt')),
            ],
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='point',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='typequestion',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='temps',
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explication de la réponse correcte'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Choix unique'), ('multiple', 'Choix multiple'), ('text', 'Réponse texte')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='texte',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_fin',
            field=models.DateTimeField(default=quiz.models.get_default_end_date),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duree',
            field=models.IntegerField(default=30, help_text='Durée en minutes'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='note_minimale',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tentatives_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='school.cours'),
        ),
        migrations.DeleteModel(
            name='Devoir',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='selected_answers',
            field=models.ManyToManyField(blank=True, to='quiz.Answer'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
    ]
