# Generated by Django 3.2.25 on 2024-12-27 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20241227_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapitre',
            options={'ordering': ['date_debut', 'titre'], 'verbose_name': 'Chapitre', 'verbose_name_plural': 'Chapitres'},
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['niveau', 'numeroClasse'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['chapitre', 'titre'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['nom'], 'verbose_name': 'Filiere', 'verbose_name_plural': 'Filieres'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['nom'], 'verbose_name': 'Matiere', 'verbose_name_plural': 'Matieres'},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['nom'], 'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AddField(
            model_name='classe',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='image',
            field=models.ImageField(null=True, upload_to='images/chapitres', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='video',
            field=models.FileField(null=True, upload_to='ressources/cours', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='cours',
            name='image',
            field=models.ImageField(null=True, upload_to='images/cours', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='cours',
            name='pdf',
            field=models.FileField(null=True, upload_to='ressources/cours', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='cours',
            name='video',
            field=models.FileField(null=True, upload_to='ressources/cours', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='image',
            field=models.ImageField(null=True, upload_to='images/matiere/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('niveau', 'numeroClasse', 'filiere')},
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Texte Enrichi'), ('image', 'Image'), ('pdf', 'Document PDF'), ('video', 'Vidéo')], max_length=10)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('file_content', models.FileField(blank=True, null=True, upload_to='course_contents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf'])])),
                ('video_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='school.cours')),
            ],
            options={
                'verbose_name': 'Contenu de cours',
                'verbose_name_plural': 'Contenus de cours',
                'ordering': ['order'],
            },
        ),
    ]
