# Generated by Django 3.2.25 on 2024-12-27 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20241227_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapitre',
            options={'ordering': ['matiere', 'ordre', 'date_debut', 'titre'], 'verbose_name': 'Chapitre', 'verbose_name_plural': 'Chapitres'},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['chapitre', 'ordre', 'titre'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.RemoveField(
            model_name='cours',
            name='pdf',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='objectifs',
            field=models.TextField(blank=True, help_text="Objectifs d'apprentissage du chapitre"),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='ordre',
            field=models.PositiveIntegerField(default=1, help_text="Ordre d'affichage du chapitre"),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='prerequis',
            field=models.TextField(blank=True, help_text='Prérequis nécessaires pour ce chapitre'),
        ),
        migrations.AddField(
            model_name='cours',
            name='duree',
            field=models.PositiveIntegerField(blank=True, help_text='Durée estimée en minutes', null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='ressources/cours', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx'])]),
        ),
        migrations.AddField(
            model_name='cours',
            name='objectifs',
            field=models.TextField(blank=True, help_text="Objectifs d'apprentissage du cours"),
        ),
        migrations.AddField(
            model_name='cours',
            name='ordre',
            field=models.PositiveIntegerField(default=1, help_text="Ordre d'affichage du cours dans le chapitre"),
        ),
        migrations.AddField(
            model_name='cours',
            name='prerequis',
            field=models.TextField(blank=True, help_text='Prérequis nécessaires pour ce cours'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='duree_en_heure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/chapitres', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ressources/cours', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='cours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cours', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='cours',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ressources/cours', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi'])]),
        ),
    ]
