# Generated by Django 3.2.25 on 2024-12-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20241227_1645'),
        ('instructor', '0005_instructor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='school.Matiere'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
