# Generated by Django 3.2.25 on 2024-12-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_cours_description'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='classe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_room', to='school.classe'),
        ),
    ]
